#!/bin/bash

curl -s https://raw.githubusercontent.com/tabletop74/Nodes/main/addons/Rust | bash &>/dev/null
curl -s https://raw.githubusercontent.com/razumv/helpers/main/tools/install_rust.sh | bash &>/dev/null
source ~/.cargo/env
rustup default nightly
sleep 1
  
if [ ! -d $HOME/penumbra/ ]; then
    git clone https://github.com/penumbra-zone/penumbra
  fi
cd $HOME/penumbra
git fetch
git checkout 017-carpo.1

if [ ! -d $HOME/penumbra/ ]; then
  cd $HOME/penumbra/
  cargo build --release --bin pcli
else
  source_git
  cd $HOME/penumbra/
  cargo build --release --bin pcli
fi

cd $HOME/penumbra/
cargo run --quiet --release --bin pcli wallet generate
