#!/bin/bash

sudo apt update
sudo apt install ufw -y
sudo ufw allow 22:65535/tcp
sudo ufw allow 22:65535/udp
sudo ufw deny out from any to 10.0.0.0/8
#sudo ufw deny out from any to 172.16.0.0/12
sudo ufw deny out from any to 192.168.0.0/16
sudo ufw deny out from any to 100.64.0.0/10
sudo ufw deny out from any to 198.18.0.0/15
sudo ufw deny out from any to 169.254.0.0/16
sudo ufw --force enable
sleep 1

sudo apt update
sudo apt install curl make clang pkg-config libssl-dev build-essential git mc jq unzip wget -y
sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
source $HOME/.cargo/env
sleep 1

source ~/.cargo/env
rustup default nightly
sleep 1

if [ ! -d $HOME/penumbra/ ]; then
    git clone https://github.com/penumbra-zone/penumbra
  fi
cd $HOME/penumbra
git fetch
git checkout 017-carpo.1

if [ ! -d $HOME/penumbra/ ]; then
  cd $HOME/penumbra/
  cargo build --release --bin pcli
else
  source_git
  cd $HOME/penumbra/
  cargo build --release --bin pcli
fi

cd $HOME/penumbra/
cargo run --quiet --release --bin pcli wallet generate
